name: onebrc_dart # apparently dart complains if name starts with a number
description: 1brc challange in dart
version: 0.0.1
repository: https://github.com/osaxma/onebrc_dart
publish_to: none

environment:
  sdk: ^3.2.3

